language: c
compiler:
  - gcc
sudo: false
addons:
  apt:
    packages:
    - cmake                                   # CMake
    - libgtk-3-dev                            # GTK+ 3
install:
  - touch remmina-plugin-to-build/CMakeLists.txt
script:
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DWITH_TRACE_CALLS=1 .
  - make
