language: c
compiler:
  - gcc
  - clang
sudo: false
addons:
  apt:
    packages:
    - cmake                                   # CMake
    - libgtk-3-dev                            # GTK+ 3
install:
  - echo install
  - cp --verbose --recursive remmina-plugin-dummy/* remmina-plugin-to-build
script:
  - echo script
  - cmake -DCMAKE_INSTALL_PREFIX=install_dir -DWITH_TRACE_CALLS=1 .
  - make
  - make install
