version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo apt update
            # Dependencies for installation
            sudo apt install cmake libgtk-3-dev
      - run:
          name: build
          command: |
            cp --verbose --recursive remmina-plugin-dummy/* remmina-plugin-to-build
            cmake -DCMAKE_INSTALL_PREFIX=install_dir -DWITH_TRACE_CALLS=ON .
            cmake --build .
            cmake --install .
